import type { Config } from "tailwindcss";

export default {
  content: ["./app/**/*.{ts,tsx}", "./components/**/*.{ts,tsx}"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-error-container": "#93000a",
        "surface-container-low": "#f7f3ea",
        "surface-dim": "#dddad1",
        "error-container": "#ffdad6",
        "primary-container": "#5d5f1b",
        "on-tertiary": "#ffffff",
        "on-secondary": "#ffffff",
        tertiary: "#52396c",
        "on-surface": "#1c1c16",
        "secondary-fixed": "#f9debd",
        "on-tertiary-container": "#e6c9ff",
        "tertiary-fixed-dim": "#dabaf7",
        "on-primary-container": "#d7d988",
        outline: "#797868",
        "on-primary": "#ffffff",
        "on-secondary-fixed-variant": "#55442c",
        "surface-container": "#f1eee4",
        "on-secondary-container": "#756147",
        "surface-variant": "#e6e2d9",
        "on-error": "#ffffff",
        "secondary-container": "#f9debd",
        "on-primary-fixed-variant": "#484a05",
        "inverse-on-surface": "#f4f1e7",
        "inverse-surface": "#31312a",
        "on-background": "#1c1c16",
        "on-primary-fixed": "#1c1d00",
        "surface-container-lowest": "#ffffff",
        "surface-tint": "#60621e",
        primary: "#454703",
        secondary: "#6e5b41",
        "surface-container-highest": "#e6e2d9",
        "surface-container-high": "#ebe8df",
        "outline-variant": "#c9c7b5",
        "on-surface-variant": "#48473a",
        "surface-bright": "#fdf9f0",
        surface: "#fdf9f0",
        error: "#ba1a1a",
        "tertiary-container": "#6b5085",
        "primary-fixed-dim": "#c9cb7b",
        "on-secondary-fixed": "#261905",
        "tertiary-fixed": "#f0dbff",
        "on-tertiary-fixed": "#280e40",
        "primary-fixed": "#e6e794",
        "on-tertiary-fixed-variant": "#553b6f",
        "secondary-fixed-dim": "#dcc3a3",
        "inverse-primary": "#c9cb7b",
        background: "#fdf9f0",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        base: "8px",
        gutter: "24px",
        "container-max": "1200px",
        lg: "48px",
        xs: "4px",
        xl: "80px",
        md: "24px",
        sm: "12px",
      },
      fontFamily: {
        "headline-lg-mobile": ["Libre Caslon Text"],
        "label-sm": ["Manrope"],
        "label-md": ["Manrope"],
        "headline-md": ["Libre Caslon Text"],
        "display-lg": ["Libre Caslon Text"],
        "body-lg": ["Manrope"],
        "body-md": ["Manrope"],
        "headline-lg": ["Libre Caslon Text"],
      },
      fontSize: {
        "headline-lg-mobile": ["28px", { lineHeight: "36px", fontWeight: "400" }],
        "label-sm": ["12px", { lineHeight: "16px", letterSpacing: "0.03em", fontWeight: "500" }],
        "label-md": ["14px", { lineHeight: "20px", letterSpacing: "0.05em", fontWeight: "600" }],
        "headline-md": ["24px", { lineHeight: "32px", fontWeight: "400" }],
        "display-lg": ["48px", { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "400" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "headline-lg": ["32px", { lineHeight: "40px", fontWeight: "400" }],
      },
    },
  },
  plugins: [require("@tailwindcss/container-queries")],
} satisfies Config;
